version: '3.8'

services:
  db:
    image: postgres:15
    container_name: inventory-service_db
    environment:
      POSTGRES_DB: inventoryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - capstone-project
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bhag1988/inventory-service:v1.0
    container_name: inventory-service_container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventoryDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8092:8092"
    networks:
      - capstone-project

networks:
  capstone-project:

volumes:
  postgres-data:
